# Generated by Django 5.2.8 on 2025-11-14 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('discord_user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('mother_language', models.CharField(choices=[('Arabic', 'ar'), ('English', 'en'), ('Spanish', 'es'), ('French', 'fr'), ('German', 'de'), ('Turkish', 'tr'), ('Russian', 'ru'), ('Hindi', 'hi'), ('Chinese (Mandarin)', 'zh'), ('Japanese', 'ja'), ('Korean', 'ko'), ('Portuguese', 'pt'), ('Italian', 'it'), ('Dutch', 'nl'), ('Swahili', 'sw')], max_length=50)),
                ('german_level', models.CharField(choices=[("I don't know anything", 'none'), ('A1 - Beginner', 'A1'), ('A2 - Elementary', 'A2'), ('B1 - Intermediate', 'B1'), ('B2 - Upper Intermediate', 'B2'), ('C1 - Advanced', 'C1'), ('C2 - Mastery / Near-native', 'C2')], default='none', max_length=50)),
                ('target_level', models.CharField(choices=[('A1 - Beginner', 'A1'), ('A2 - Elementary', 'A2'), ('B1 - Intermediate', 'B1'), ('B2 - Upper Intermediate', 'B2'), ('C1 - Advanced', 'C1'), ('C2 - Mastery / Near-native', 'C2')], max_length=50)),
                ('correction_style', models.CharField(choices=[('Gentle', 'gentle'), ('Direct', 'direct'), ('Explanatory', 'explanatory'), ('Minimal', 'minimal'), ('Native-like', 'native')], max_length=50)),
                ('onboarding_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_active_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
