# Generated by Django 5.2.8 on 2025-11-14 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schnack', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Discord_Profile',
        ),
    ]
