# Generated by Django 5.2.8 on 2025-11-14 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Discord_Profile',
            new_name='DiscordProfile',
        ),
    ]
