# Generated by Django 5.2.8 on 2025-11-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_rename_discord_profile_discordprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordprofile',
            name='discord_user_id',
            field=models.BigIntegerField(max_length=18, primary_key=True, serialize=False, unique=True),
        ),
    ]
