# Generated by Django 5.2.8 on 2025-11-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_discordprofile_discord_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordprofile',
            name='german_level',
            field=models.CharField(choices=[('none', "I don't know anything"), ('A1', 'A1 - Beginner'), ('A2', 'A2 - Elementary'), ('B1', 'B1 - Intermediate'), ('B2', 'B2 - Upper Intermediate'), ('C1', 'C1 - Advanced'), ('C2', 'C2 - Mastery / Near-native')], default='none', max_length=50),
        ),
    ]
