# Generated by Django 5.2.8 on 2025-11-15 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_discordprofile_german_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordprofile',
            name='correction_style',
            field=models.CharField(choices=[('gentle', 'Gentle'), ('direct', 'Direct'), ('explanatory', 'Explanatory'), ('minimal', 'Minimal'), ('native-like', 'Native')], max_length=50),
        ),
        migrations.AlterField(
            model_name='discordprofile',
            name='mother_language',
            field=models.CharField(choices=[('arabic', 'Arabic'), ('english', 'English'), ('spanish', 'Spanish'), ('french', 'French'), ('german', 'German'), ('turkish', 'Turkish'), ('russian', 'Russian'), ('hindi', 'Hindi'), ('chinese (mandarin)', 'Chinese (Mandarin)'), ('japanese', 'Japanese'), ('korean', 'Korean'), ('portuguese', 'Portuguese'), ('italian', 'Italian'), ('dutch', 'Dutch'), ('swahili', 'Swahili')], max_length=50),
        ),
        migrations.AlterField(
            model_name='discordprofile',
            name='target_level',
            field=models.CharField(choices=[('A1', 'A1 - Beginner'), ('A2', 'A2 - Elementary'), ('B1', 'B1 - Intermediate'), ('B2', 'B2 - Upper Intermediate'), ('C1', 'C1 - Advanced'), ('C2', 'C2 - Mastery / Near-native')], max_length=50),
        ),
    ]
