# Generated by Django 5.2.8 on 2025-11-15 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_discordprofile_correction_style_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordprofile',
            name='correction_style',
            field=models.CharField(choices=[('Gentle', 'gentle'), ('Direct', 'direct'), ('Explanatory', 'explanatory'), ('Minimal', 'minimal'), ('Native-like', 'native')], max_length=50),
        ),
        migrations.AlterField(
            model_name='discordprofile',
            name='german_level',
            field=models.CharField(choices=[('none', "I don't know anything – Start with basic greetings and alphabet."), ('A1', 'A1 - Beginner – Focus on simple sentences and common verbs.'), ('A2', 'A2 - Elementary – Introduce past tense and everyday vocabulary.'), ('B1', 'B1 - Intermediate – Practice conversations and grammar nuances.'), ('B2', 'B2 - Upper Intermediate – Refine fluency and handle abstract topics.'), ('C1', 'C1 - Advanced – Work on precision, idioms, and native-like flow.'), ('C2', 'C2 - Mastery / Near-native – Challenge with native-level texts and debates.')], max_length=50),
        ),
        migrations.AlterField(
            model_name='discordprofile',
            name='mother_language',
            field=models.CharField(choices=[('Arabic', 'arabic'), ('English', 'english'), ('Spanish', 'spanish'), ('French', 'french'), ('German', 'german'), ('Turkish', 'turkish'), ('Russian', 'russian'), ('Hindi', 'hindi'), ('Chinese (Mandarin)', 'chinese (mandarin)'), ('Japanese', 'japanese'), ('Korean', 'korean'), ('Portuguese', 'portuguese'), ('Italian', 'italian'), ('Dutch', 'dutch'), ('Swahili', 'swahili')], max_length=50),
        ),
        migrations.AlterField(
            model_name='discordprofile',
            name='target_level',
            field=models.CharField(choices=[('A1 - Beginner', 'A1'), ('A2 - Elementary', 'A2'), ('B1 - Intermediate', 'B1'), ('B2 - Upper Intermediate', 'B2'), ('C1 - Advanced', 'C1'), ('C2 - Mastery / Near-native', 'C2')], max_length=50),
        ),
    ]
