# Generated by Django 5.2.8 on 2025-11-15 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_discordprofile_correction_style_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordprofile',
            name='german_level',
            field=models.CharField(choices=[("I don't know anything – Start with basic greetings and alphabet.", 'none'), ('A1 - Beginner – Focus on simple sentences and common verbs.', 'A1'), ('A2 - Elementary – Introduce past tense and everyday vocabulary.', 'A2'), ('B1 - Intermediate – Practice conversations and grammar nuances.', 'B1'), ('B2 - Upper Intermediate – Refine fluency and handle abstract topics.', 'B2'), ('C1 - Advanced – Work on precision, idioms, and native-like flow.', 'C1'), ('C2 - Mastery / Near-native – Challenge with native-level texts and debates.', 'C2')], max_length=100),
        ),
    ]
