# Generated by Django 5.2.8 on 2025-11-15 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_discordprofile_german_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordprofile',
            name='correction_style',
            field=models.CharField(choices=[('Gentle', 'gentle'), ('Direct', 'direct'), ('Explanatory', 'explanatory'), ('Minimal', 'minimal')], max_length=50),
        ),
        migrations.AlterField(
            model_name='discordprofile',
            name='german_level',
            field=models.CharField(choices=[('I know nothing - Start with basic greetings and alphabet.', 'none'), ('A1 - Focus on simple sentences and common verbs.', 'A1'), ('A2 - Introduce past tense and everyday vocabulary.', 'A2'), ('B1 - Practice conversations and grammar nuances.', 'B1'), ('B2 - Refine fluency and handle abstract topics.', 'B2'), ('C1 - Work on precision, idioms, and native-like flow.', 'C1'), ('C2 - Challenge with native-level texts and debates.', 'C2')], max_length=100),
        ),
    ]
