# Generated by Django 5.2.8 on 2025-11-15 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_discordprofile_correction_style_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordprofile',
            name='dicord_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='discordprofile',
            name='discord_user_id',
            field=models.IntegerField(max_length=18, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='discordprofile',
            name='german_level',
            field=models.CharField(choices=[('I know nothing - Start with basic greetings and alphabet.', 'none'), ('A1 - Focus on simple sentences and common verbs.', 'a1'), ('A2 - Introduce past tense and everyday vocabulary.', 'a2'), ('B1 - Practice conversations and grammar nuances.', 'b1'), ('B2 - Refine fluency and handle abstract topics.', 'b2'), ('C1 - Work on precision, idioms, and native-like flow.', 'c1'), ('C2 - Challenge with native-level texts and debates.', 'c2')], max_length=100),
        ),
        migrations.AlterField(
            model_name='discordprofile',
            name='target_level',
            field=models.CharField(choices=[('A1 - Beginner', 'a1'), ('A2 - Elementary', 'a2'), ('B1 - Intermediate', 'b1'), ('B2 - Upper Intermediate', 'b2'), ('C1 - Advanced', 'c1'), ('C2 - Mastery / Near-native', 'c2')], max_length=50),
        ),
    ]
