# Generated by Django 5.2.8 on 2025-11-15 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_discordprofile_dicord_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordprofile',
            name='dicord_username',
            field=models.CharField(blank=True, null=True),
        ),
    ]
