# Generated by Django 5.2.8 on 2025-11-15 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_alter_discordprofile_dicord_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discordprofile',
            old_name='dicord_username',
            new_name='discord_username',
        ),
    ]
