# Generated by Django 5.2.8 on 2025-11-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_rename_dicord_username_discordprofile_discord_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordprofile',
            name='discord_user_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
