# Generated by Django 5.2.8 on 2025-11-16 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_messagehistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagehistory',
            old_name='bot_message',
            new_name='schnack_response',
        ),
    ]
