# Generated by Django 5.2.8 on 2025-11-17 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_rename_bot_message_messagehistory_schnack_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagehistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_message_history', to='profiles.discordprofile'),
        ),
    ]
