# Generated by Django 5.2.8 on 2025-11-14 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='correction_style',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='discord_user_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='german_level',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_active_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mother_language',
        ),
        migrations.RemoveField(
            model_name='user',
            name='onboarding_complete',
        ),
        migrations.RemoveField(
            model_name='user',
            name='target_level',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
